# Generated by Django 4.0.4 on 2023-05-04 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('currency_type', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
