# Generated by Django 4.0.4 on 2023-05-04 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cui', models.CharField(help_text='Cod Unic de Inregistrare, codul fiscal', max_length=12, unique=True)),
                ('nrRegCom', models.CharField(help_text='Numar inregistrare registrul comertului', max_length=40, unique=True)),
                ('denumire', models.CharField(help_text='Nume societate', max_length=250)),
                ('judet', models.CharField(blank=True, help_text='judet', max_length=250)),
                ('oras', models.CharField(blank=True, help_text='oras', max_length=250)),
                ('strada', models.CharField(blank=True, help_text='strada', max_length=250)),
                ('nr', models.CharField(blank=True, help_text='nr', max_length=10)),
                ('bloc', models.CharField(blank=True, help_text='bloc', max_length=10)),
                ('ap', models.CharField(blank=True, help_text='apartament', max_length=10)),
                ('etaj', models.CharField(blank=True, help_text='etaj', max_length=10)),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None, verbose_name='Numar de telefon')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Fax', max_length=128, region=None, verbose_name='Fax')),
                ('codPostal', models.CharField(blank=True, help_text='cod postal', max_length=10, verbose_name='cod postal')),
                ('scopTVA', models.BooleanField(default=False, help_text='true -pentru platitor in scopuri de tva / false in cazul in care nu e platitor  in scopuri de TVA la data cautata', verbose_name='platitor TVA')),
                ('statusTvaIncasare', models.BooleanField(default=False, help_text='true -pentru platitor in scopuri de tva / false in cazul in care nu e platitor  in scopuri de TVA la data cautata', verbose_name='TVA la incasare')),
                ('statusSplitTVA', models.BooleanField(default=False, help_text='true -pentru platitor in scopuri de tva / false in cazul in care nu e platitor  in scopuri de TVA la data cautata', verbose_name='split TVA')),
                ('cotaTVA', models.DecimalField(decimal_places=0, help_text='Cota TVA', max_digits=2, verbose_name='cota de tva')),
                ('iban', models.CharField(blank=True, help_text='Contul Iban', max_length=16, verbose_name='contul IBAN')),
                ('banca', models.CharField(blank=True, help_text='Banca', max_length=50, verbose_name='banca')),
                ('slug', models.SlugField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
            ],
            options={
                'verbose_name': 'Companie',
                'verbose_name_plural': 'Companii',
                'db_table': 'my_company',
            },
        ),
        migrations.CreateModel(
            name='UsersAndCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_to_user', to='my_company.mycompany')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compania mea',
                'verbose_name_plural': 'Companiile mele',
                'db_table': 'users_and_company',
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='CurrentCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=False, help_text='Comania curenta pe care se lucreaza')),
                ('slug', models.SlugField()),
                ('current_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UsersAndCompany', to='my_company.usersandcompany')),
            ],
            options={
                'verbose_name': 'Compania curenta',
                'verbose_name_plural': 'Companie curenta',
                'db_table': 'current_company',
            },
        ),
    ]
