# Generated by Django 4.0.4 on 2023-05-04 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Factura'), ('PROFORMA', 'Proforma'), ('RECEIPT', 'chitata')], default='INVOICE', max_length=64, verbose_name='tip document')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='serie document')),
                ('star_value', models.DecimalField(decimal_places=0, default=1, max_digits=5, verbose_name='Primul numar')),
                ('end_value', models.DecimalField(decimal_places=0, default=99999, max_digits=5, verbose_name='Ultimul numar')),
                ('last_insert', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Ultimul introdus')),
                ('next_value', models.DecimalField(decimal_places=0, default=1, max_digits=5, verbose_name='Urmatorul')),
                ('slug', models.SlugField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_series_to_company', to='my_company.mycompany', verbose_name='firma')),
            ],
            options={
                'verbose_name': 'Serie document',
                'verbose_name_plural': 'Serie documente',
                'unique_together': {('company', 'series', 'doc_type', 'star_value')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('type', models.CharField(choices=[('INVOICE', 'Factura'), ('PROFORMA', 'Proforma'), ('RECEIPT', 'chitata')], default='INVOICE', max_length=64, verbose_name='tip')),
                ('series', models.CharField(blank=True, max_length=10, null=True, verbose_name='serie factura')),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='numar facura')),
                ('status', models.CharField(choices=[('NEW', 'nou'), ('SENT', 'trimis'), ('RETURNED', 'returnat'), ('CANCELED', 'anulat'), ('PAID', 'platita')], default='NEW', max_length=64, verbose_name='status')),
                ('related_document', models.CharField(blank=True, max_length=100, verbose_name='documente legate')),
                ('note', models.CharField(blank=True, default='Multumim!', max_length=255, verbose_name='note')),
                ('date_issue', models.DateField(default=django.utils.timezone.now, verbose_name='data emiteri')),
                ('date_due', models.DateField(default=datetime.datetime(2023, 5, 19, 14, 0, 14, 937115, tzinfo=utc), help_text='de achitat pana la', verbose_name='data scadentei')),
                ('delivery_method', models.CharField(choices=[('PERSONAL_PICKUP', 'ridicare personala'), ('MAILING', 'curier / posta'), ('DIGITAL', 'digital')], default='PERSONAL_PICKUP', max_length=64, verbose_name='mod de livrare')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='TVA')),
                ('slug', models.SlugField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_to_customer', to='customers.customer', verbose_name='Client')),
                ('series_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_to_doc_series', to='invoice.documentseries', verbose_name='serie document')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_to_company', to='my_company.mycompany', verbose_name='Furnizor')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturi',
                'ordering': ('date_issue', 'series', 'number'),
                'default_permissions': ('list', 'view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='VatValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('vat_value', models.DecimalField(decimal_places=0, default=19, max_digits=3, verbose_name='TVA')),
                ('short_desc', models.CharField(blank=True, max_length=10, verbose_name='descriere')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descriere')),
            ],
            options={
                'verbose_name': 'TVA',
                'verbose_name_plural': 'TVA',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Ultima modificare')),
                ('is_active', models.BooleanField(default=True, help_text='Modelul de tiparire este disponibil pentru tiparire')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Produs/serviciu')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='cantitate')),
                ('unit', models.CharField(choices=[('EMPTY', ''), ('PIECES', 'buc'), ('HOURS', 'ora')], default='PIECES', max_length=64, verbose_name='UM')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pret pe bucata')),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='reducere (%)')),
                ('tax_rate', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='TVA (%)')),
                ('tag', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='tag')),
                ('is_vat_included', models.BooleanField(default=False, help_text='include TVA ', verbose_name='include TVA %')),
                ('weight', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=0, help_text='ordering', null=True, verbose_name='weight')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', verbose_name='invoice')),
                ('tax_rate_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.vatvalue', verbose_name='Tip TVA %')),
            ],
            options={
                'verbose_name': 'produs/serviciu',
                'verbose_name_plural': 'produse / servicii',
                'db_table': 'invoice_items',
                'ordering': ('-invoice', 'created_at'),
            },
        ),
    ]
