# Generated by Django 4.0.4 on 2023-05-04 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 14, 8, 14, 32652, tzinfo=utc), help_text='de achitat pana la', verbose_name='data scadentei'),
        ),
    ]
